<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Temel boyutlar -->
    <xacro:property name="base_width" value="0.6"/>
    <xacro:property name="base_length" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>

    <!-- Tekerlek boyutları -->
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="caster_wheel_radius" value="0.05"/>

    <!-- Hesaplanan yardımcı değişkenler (okunabilirlik için) -->
    <xacro:property name="base_z" value="${(base_height/2) + wheel_radius}"/>
    <xacro:property name="wheel_x" value="${-(base_width/2) + wheel_radius}"/>
    <xacro:property name="wheel_y_offset" value="${(base_length/2) + (wheel_length/2)}"/>
    <xacro:property name="wheel_z" value="${-wheel_radius}"/>
    <xacro:property name="caster_z" value="${-((base_height/2) + caster_wheel_radius)}"/>

    <!-- Base reference -->
    <link name="base_footprint"/>

    <!-- Base gövdesi -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="cyan"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <!-- Tekerlek makrosu -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </link>
    </xacro:macro>

    <!-- Tekerlek linkleri -->
    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <!-- Caster tekerlek -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertia m="0.5" r="${2*caster_wheel_radius}" xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <!-- Eklem tanımları (hesaplanan property'leri kullanarak sadeleştirildi) -->
    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_z}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${wheel_x} ${-wheel_y_offset} ${wheel_z}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${wheel_x} ${wheel_y_offset} ${wheel_z}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="0.2 0 ${caster_z}" rpy="0 0 0"/>
    </joint>

</robot>